import builtins from 'builtin-modules';
import chokidar from 'chokidar';
import 'dotenv/config';
import esbuild from 'esbuild';
import copy from 'esbuild-plugin-copy';
import fs from 'fs-jetpack';
import { transform } from 'lightningcss';
import { basename } from 'path';
import process from 'process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'esnext',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
  outfile: 'dist/main.js',
  define: {
    __DEV_MODE__ : JSON.stringify(!prod),
  },
  plugins: [
    copy({
      resolveFrom: 'cwd',
      assets: [
        {
          from: ['./manifest.json'],
          to: ['./dist/manifest.json'],
        },
      ],
      watch: true,
    }),
  ],
});

const distDir = fs.path('.', 'dist');

async function watchCopyToVault() {
  if (!process.env.OBSIDIAN_VAULT) {
    console.error('No OBSIDIAN_VAULT env provided, will not sync to vault.');
    return;
  }
  const pluginDir = fs.path(
    process.env.OBSIDIAN_VAULT,
    '.obsidian',
    'plugins',
    'update-time-on-edit',
  );

  if (!fs.exists(pluginDir)) {
    console.error('No plugin dir found. Skipping local install.');
    return;
  }

  const onTrigger = (path: string) => {
    const dist = fs.path(pluginDir, basename(path));
    fs.copy(path, dist, { overwrite: true });
    console.log(`[obsidian] ${path} -> ${dist}`);
  };

  const watcher = chokidar.watch(distDir);
  watcher.on('change', onTrigger);
  watcher.on('add', onTrigger);
}

// Call this once per build.
const sourceCssFilePath = fs.path('.', 'styles.css');

async function processCss() {
  const content = fs.read(sourceCssFilePath, 'buffer');
  if (!content) {
    console.error(`[css] source file not found: ${sourceCssFilePath}`);
    return;
  }
  const uint8 = new Uint8Array(content);
  const { code } = transform({
    filename: 'style.css',
    code: uint8,
    minify: true,
    sourceMap: false,
  });
  fs.write(fs.path(distDir, 'styles.css'), code);
  console.log('[css] compiled css');
}

async function watchCssChanges() {
  const watcher = chokidar.watch(sourceCssFilePath);
  watcher.on('add', processCss);
  watcher.on('change', processCss);
}

if (prod) {
  await context.rebuild();
  await processCss();
  process.exit(0);
} else {
  await Promise.all([watchCopyToVault(), watchCssChanges(), context.watch()]);
}
